### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by airween** [MengRao/TCP-UDP-Proxy#1]
Hi,
I've tried to compile the source, the result is:

```bash
# make
g++ -I .  -Wall -Werror -O3 -c -o ServerArgsBase.o ServerArgsBase.cpp
g++ -I .  -Wall -Werror -O3 -c -o xthread.o xthread.cpp
g++ -I .  -Wall -Werror -O3 -c -o shared_data.o shared_data.cpp
In file included from udp_proxy.h:3:0,
                 from shared_data.h:5,
                 from shared_data.cpp:1:
buffer.h: In member function ‘global::Buffer::operator bool() const’:
buffer.h:89:11: error: cannot convert ‘const boost::shared_array<unsigned char>’ to ‘bool’ in return
    return buf;
           ^~~
Makefile:44: recipe for target 'shared_data.o' failed
make: *** [shared_data.o] Error 1
```

What would be the problem?

Thanks,

a.

**Comment by otavioarj** [comment]
Fixes :)
In buffer.h:89:
`return (bool) buf_size;`

In Makefile change -lpthread to just -pthread. Changing -O3 to -Ofast gave me about 1-2ms less latency, probably it's about Boost heavyweight approach when dealing with vectors :(

**Comment by MengRao** [comment]
Thanks for the fixing, and I've updated the code. This tool is out of maintenance for years(sry...) and it was based on relatively old g++ and boost lib, hope it works well :)
